#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "flaresolverr"
name = "FlareSolverr"
description.en = "Proxy server to bypass Cloudflare and DDoS-GUARD protection"
description.fr = "Serveur proxy pour contourner Cloudlare et la protection DDoS-GUARD"

version = "3.3.21~ynh1"

maintainers = ["Tigui14"]

[upstream]
license = "MIT"
website = "https://github.com/FlareSolverr/FlareSolverr"
admindoc = "https://github.com/FlareSolverr/FlareSolverr"
code = "https://github.com/FlareSolverr/FlareSolverr"

[integration]
yunohost = ">= 12.0"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/flaresolverr"

[resources]
    [resources.sources.main]
    amd64.url = "https://github.com/FlareSolverr/FlareSolverr/releases/download/v3.3.21/flaresolverr_linux_x64.tar.gz"
    amd64.sha256 = "e6f34cfa8047561e5c11080cdb6515e71776b5c5bb4e391336972ccc7368c4d6"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*\\.linux-x64.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
    main.allowed = "admins"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages = [
        "sqlite3",
        "dirmngr",
        "mediainfo",
    ]
